### ISSUE TITLE
genesis.json file does not have the public and private key info

### ISSUE THREAD

**Issue by ToniyaSundaram** [gallactic/gallactic#77]
To do any transaction an account needs a private key with balance. In genesis.json I have an account with initial balance but to do transaction I do not have the public or private key.  Would it be possible to provide other information as well ?
![screenshot 2018-12-04 at 4 33 30 pm](https://user-images.githubusercontent.com/24692131/49428974-60975480-f7e2-11e8-9717-bd16f438d10d.png)

**Comment by b00f** [comment]
This happens when the user uses `init` command to generate config and genesis files for running Gallactic. In this case we need to save the accounts' `key` files. We can save it under `~/gallactic/keystore` or inside working directory.
